### DISCUSSION TITLE
Elixir library no longer updated/published to hex.pm

### DISCUSSION THREAD

**Discussion by vitalis** [cucumber/common#2218] [General]
I noticed that the last published version was [25.0.2](https://hex.pm/packages/cucumber_gherkin/25.0.2) on Nov 09, 2022

**Comment by mpkorstanje** [comment]
That's correct! I couldn't find a version of OTP and Elixir that worked on Ubuntu latest as provided by GitHub.

We're also a bit short on contributors with Elixir knowledge and time to spare. 

If you could take https://github.com/cucumber/gherkin/pull/72 and find a combination of versions that does, and possibly upgrade the project itself we could start publishing again.

**Reply by vitalis** [reply]
@mpkorstanje the following setups work for me, I'm sure they will also work with the latest Ubuntu:
https://raw.githubusercontent.com/vitalis/lumaai_ex/refs/heads/main/.github/workflows/tests.yml

If you want I can create a PR

**Reply by mpkorstanje** [reply]
Please do!

**Reply by vitalis** [reply]
https://github.com/vitalis/gherkin/actions/runs/11808873255

**Reply by vitalis** [reply]
https://github.com/cucumber/gherkin/pull/313

**Reply by vitalis** [reply]
If I can help more, just tell me what you need ;)

**Reply by mpkorstanje** [reply]
Actually yes. Gherkin uses Cucumber Messages. It is a set of DTOs + a json schema that we're in the process of adding to Cucumber implementations so we can have a common report format.

The fix we used to get Gherkin to build [does not work on messages](https://github.com/cucumber/messages/pull/265), and I reckon once that is fixed and released, Gherkin could do with an update to the latest version of messages.

If you're interested, feel free!

**Reply by vitalis** [reply]
@mpkorstanje It's not working because you are using the same steps as for the Gherkin:
```yaml
      - run: |
          mix deps.get
        working-directory: elixir
      - run: mix test
        working-directory: elixir

      - name: run acceptance tests
        run: make acceptance
        working-directory: 'elixir'
```
        
 You need to run the "Make" tasks defined in 'default.mk'
 The reason is there is a code that being generated with the make tasks
